### PR TITLE
Fix link failure on non-ADC targets from unconditional checkBatteryVoltageState() call

### PR DESCRIPTION
**Pull request by sensei-hacker**
## Summary

`checkBatteryVoltageState()` is defined only inside `#ifdef USE_ADC` in `src/main/sensors/battery.c`, but two call sites invoked it unconditionally:

- `src/main/io/osd.c` — `osdDisplayBatteryVoltage()`
- `src/main/fc/multifunction.c` — the low-battery-voltage warning check

Any target that doesn't define `USE_ADC` fails to link with `undefined reference to checkBatteryVoltageState`. This affects COLIBRI and QUANTON, which have no analog battery-voltage sensing hardware at all. Bisected the regression to commit f3de64444a0 ("osd batt cleanup", 2023-02-07), which extracted the voltage-state check out of the always-defined `getBatteryState()` path into the new ADC-only function without updating these two unconditional callers. It went unnoticed because both affected targets are `SKIP_RELEASES` and aren't in the normal release build sweep.

## Changes

- Both call sites now use `getBatteryState()` instead, which is defined unconditionally and returns the same cached state. `multifunction.c` already uses `getBatteryState()` two lines later for the equivalent capacity-based warning check, so this also makes the two checks consistent with each other.

## Testing

- COLIBRI and QUANTON: previously failed to link, now build and link cleanly.
- MATEKF405, OMNIBUSF4, KAKUTEF7 (ADC-equipped): confirmed no regression, build cleanly with no new warnings.

### CODE REVIEW

**Comment by breadoven** [comment]
This isn't the right way to fix this. `checkBatteryVoltageState `specifically handles voltage whereas `getBatteryState `doesn't, it could just be capacity based if capacity is used.

Probably best to just make multifunction and OSD voltage conditional on `USE_ADC `surely ? If there's no voltage available there's nothing to display.

**Comment by sensei-hacker** [comment]
> This isn't the right way to fix this. `checkBatteryVoltageState `specifically handles voltage whereas `getBatteryState `doesn't, it could just be capacity based if capacity is used.
> 
> Probably best to just make multifunction and OSD voltage conditional on `USE_ADC `surely ? If there's no voltage available there's nothing to display.

Thank you!

**Comment by sensei-hacker** [comment]
Good catch, thanks! Pushed a fix. Both call sites now use `checkBatteryVoltageState()` again, guarded by `#ifdef USE_ADC`
