### ISSUE TITLE
Auto Declination build regression with a451e0e

### ISSUE THREAD

**Issue by stronnag** [iNavFlight/inav#182]
As of 2016-05-03, master (a451e0e) fails to build with `INAV_ENABLE_AUTO_MAG_DECLINATION=1`

```
 In function `onNewGPSData':
inav/./src/main/flight/navigation_rewrite_pos_estimator.c:281: undefined reference to `geoCalculateMagDeclination'
collect2: error: ld returned 1 exit status
```

(this on SPRF3 target)
